spring:
    hadoop:
        fsUri: hdfs://sandbox-hdp.hortonworks.com:8020
        resourceManagerHost: sandbox-hdp.hortonworks.com
    yarn:
        appName: gs-yarn-basic
        applicationDir: /app/gs-yarn-basic/
        client:
            files:
              - "file:container-1.0.0.jar"
              - "file:appmaster-1.0.0.jar"
            launchcontext:
                archiveFile: appmaster-1.0.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: container-1.0.0.jar
